Mode: dev
Application:
  Domain: localhost:8990
  Host: 127.0.0.1
  IsHttps: false
  Name: melancholy
  Port: "8002"
  ReadTimeout: 1
  WriterTimeout: 2
Database:
  Dbtype: mysql
  Host: 127.0.0.1
  Port: 3306
  Name: melancholy
  Password: your password
  Username: ferry
Gorm:
  LogMode: 0
  MaxIdleConn: 0
  MaxOpenConn: 20000