Mode: debug
Application:
  Domain: localhost:8990
  Host: localhost
  IsHttps: false
  Name: melancholy
  Port: "8002"
  ReadTimeout: 10
  WriterTimeout: 10
  LocationUnix: ~/melancholy/
  LocationWin: ../melancholyStorage/saveFiles/
  TmpFile: ~/melancholyStorage/tmp/
  AppSecret: 43f776358a
  AppIss: github.com/HaHadaxigua/melancholy
Database:
  Dbtype: mysql
  Host: 127.0.0.1
  Port: 3307
  Name: melancholy
  Password: 123456
  Username: root
Gorm:
  LogMode: 0
  MaxIdleConn: 0
  MaxOpenConn: 20000
OSS:
  EndPoint: oss-cn-shanghai.aliyuncs.com
  AccessKeyID: LTAI5tBGyku7RiUc7GGkgs5z
  AccessKeySecret: NMXytPtkTHaD9UFcdkiopOObfntUI0
Cloud:
  AccessKeyID: LTAI5tDDoxSXNHP6SV4ZTvTc
  AccessKeySecret: KfBBI8K5udgDEGk7lIAoIceO7EXGyB
FileSupport:
  List:
    - ".txt"
    - ".sh"
    - ".png"