Mode: debug
Application:
  Domain: localhost:8990
  Host: localhost
  IsHttps: false
  Name: melancholy
  Port: "8002"
  ReadTimeout: 1
  WriterTimeout: 2
  Location: ~/install/
  AppSecret: 43f776358a
  AppIss: github.com/HaHadaxigua/melancholy
Database:
  Dbtype: mysql
  Host: 127.0.0.1
  Port: 3307
  Name: melancholy
  Password: 123456
  Username: root
Gorm:
  LogMode: 0
  MaxIdleConn: 0
  MaxOpenConn: 20000
OSS:
  EndPoint: http://oss-cn-shanghai.aliyuncs.com
  AccessKeyID: LTAI4G2LaueUq1PHhpL4wzUx
  AccessKeySecret: d3Hkx1HmhVippntj5fsONwchvKWkHK
  BucketName: test