Mode: debug
Application:
  Domain: localhost:8990
  Host: localhost
  IsHttps: false
  Name: melancholy
  Port: "8002"
  ReadTimeout: 1
  WriterTimeout: 2
  Location: ~/melancholy/
  TmpFile: ~/melancholy/tmp/
  AppSecret: 43f776358a
  AppIss: github.com/HaHadaxigua/melancholy
Database:
  Dbtype: mysql
  Host: sh-cdb-r9u1s7k2.sql.tencentcdb.com
  Port: 60246
  Name: melancholy
  Password: r-N2_PrMAJzzkeQ
  Username: root
Gorm:
  LogMode: 0
  MaxIdleConn: 0
  MaxOpenConn: 20000
OSS:
  EndPoint:
  AccessKeyID:
  AccessKeySecret: