Mode: debug
Application:
  Domain: localhost:8990
  Host: localhost
  IsHttps: false
  Name: melancholy
  Port: "8002"
  ReadTimeout: 1
  WriterTimeout: 2
  Location: ~/install/
  AppSecret: 43f776358a
  AppIss: github.com/HaHadaxigua/melancholy
Database:
  Dbtype:
  Host:
  Port:
  Name:
  Password:
  Username:
Gorm:
  LogMode: 0
  MaxIdleConn: 0
  MaxOpenConn: 20000
OSS:
  EndPoint:
  AccessKeyID:
  AccessKeySecret:
  BucketName: