// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/HaHadaxigua/melancholy/ent/exitlog"
	"github.com/HaHadaxigua/melancholy/ent/folder"
	"github.com/HaHadaxigua/melancholy/ent/mfile"
	"github.com/HaHadaxigua/melancholy/ent/role"
	"github.com/HaHadaxigua/melancholy/ent/schema"
	"github.com/HaHadaxigua/melancholy/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	exitlogFields := schema.ExitLog{}.Fields()
	_ = exitlogFields
	// exitlogDescDate is the schema descriptor for date field.
	exitlogDescDate := exitlogFields[3].Descriptor()
	// exitlog.DefaultDate holds the default value on creation for the date field.
	exitlog.DefaultDate = exitlogDescDate.Default.(func() time.Time)
	folderFields := schema.Folder{}.Fields()
	_ = folderFields
	// folderDescSize is the schema descriptor for size field.
	folderDescSize := folderFields[4].Descriptor()
	// folder.DefaultSize holds the default value on creation for the size field.
	folder.DefaultSize = folderDescSize.Default.(int)
	// folderDescCreatedAt is the schema descriptor for created_at field.
	folderDescCreatedAt := folderFields[6].Descriptor()
	// folder.DefaultCreatedAt holds the default value on creation for the created_at field.
	folder.DefaultCreatedAt = folderDescCreatedAt.Default.(func() time.Time)
	// folderDescUpdatedAt is the schema descriptor for updated_at field.
	folderDescUpdatedAt := folderFields[7].Descriptor()
	// folder.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	folder.DefaultUpdatedAt = folderDescUpdatedAt.Default.(func() time.Time)
	// folder.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	folder.UpdateDefaultUpdatedAt = folderDescUpdatedAt.UpdateDefault.(func() time.Time)
	mfileFields := schema.MFile{}.Fields()
	_ = mfileFields
	// mfileDescSize is the schema descriptor for size field.
	mfileDescSize := mfileFields[5].Descriptor()
	// mfile.DefaultSize holds the default value on creation for the size field.
	mfile.DefaultSize = mfileDescSize.Default.(int)
	// mfileDescDesc is the schema descriptor for desc field.
	mfileDescDesc := mfileFields[7].Descriptor()
	// mfile.DefaultDesc holds the default value on creation for the desc field.
	mfile.DefaultDesc = mfileDescDesc.Default.(string)
	// mfileDescCreatedAt is the schema descriptor for created_at field.
	mfileDescCreatedAt := mfileFields[9].Descriptor()
	// mfile.DefaultCreatedAt holds the default value on creation for the created_at field.
	mfile.DefaultCreatedAt = mfileDescCreatedAt.Default.(func() time.Time)
	// mfileDescUpdatedAt is the schema descriptor for updated_at field.
	mfileDescUpdatedAt := mfileFields[10].Descriptor()
	// mfile.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	mfile.DefaultUpdatedAt = mfileDescUpdatedAt.Default.(func() time.Time)
	// mfile.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	mfile.UpdateDefaultUpdatedAt = mfileDescUpdatedAt.UpdateDefault.(func() time.Time)
	roleFields := schema.Role{}.Fields()
	_ = roleFields
	// roleDescCreatedAt is the schema descriptor for created_at field.
	roleDescCreatedAt := roleFields[3].Descriptor()
	// role.DefaultCreatedAt holds the default value on creation for the created_at field.
	role.DefaultCreatedAt = roleDescCreatedAt.Default.(func() time.Time)
	// roleDescUpdatedAt is the schema descriptor for updated_at field.
	roleDescUpdatedAt := roleFields[4].Descriptor()
	// role.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	role.DefaultUpdatedAt = roleDescUpdatedAt.Default.(func() time.Time)
	// role.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	role.UpdateDefaultUpdatedAt = roleDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[7].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[8].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
