// Code generated by entc, DO NOT EDIT.

package exitlog

import (
	"time"
)

const (
	// Label holds the string label denoting the exitlog type in the database.
	Label = "exit_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldToken holds the string denoting the token field in the database.
	FieldToken = "token"
	// FieldDate holds the string denoting the date field in the database.
	FieldDate = "date"

	// Table holds the table name of the exitlog in the database.
	Table = "exit_logs"
)

// Columns holds all SQL columns for exitlog fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldToken,
	FieldDate,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the ExitLog type.
var ForeignKeys = []string{
	"user_exitlogs",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultDate holds the default value on creation for the date field.
	DefaultDate func() time.Time
)
