// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/HaHadaxigua/melancholy/ent/exitlog"
	"github.com/HaHadaxigua/melancholy/ent/predicate"
	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
)

// ExitLogDelete is the builder for deleting a ExitLog entity.
type ExitLogDelete struct {
	config
	hooks    []Hook
	mutation *ExitLogMutation
}

// Where adds a new predicate to the delete builder.
func (eld *ExitLogDelete) Where(ps ...predicate.ExitLog) *ExitLogDelete {
	eld.mutation.predicates = append(eld.mutation.predicates, ps...)
	return eld
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (eld *ExitLogDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(eld.hooks) == 0 {
		affected, err = eld.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ExitLogMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			eld.mutation = mutation
			affected, err = eld.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(eld.hooks) - 1; i >= 0; i-- {
			mut = eld.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, eld.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (eld *ExitLogDelete) ExecX(ctx context.Context) int {
	n, err := eld.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (eld *ExitLogDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: exitlog.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: exitlog.FieldID,
			},
		},
	}
	if ps := eld.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, eld.driver, _spec)
}

// ExitLogDeleteOne is the builder for deleting a single ExitLog entity.
type ExitLogDeleteOne struct {
	eld *ExitLogDelete
}

// Exec executes the deletion query.
func (eldo *ExitLogDeleteOne) Exec(ctx context.Context) error {
	n, err := eldo.eld.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{exitlog.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (eldo *ExitLogDeleteOne) ExecX(ctx context.Context) {
	eldo.eld.ExecX(ctx)
}
