basePath: /handler/v1
host: 127.0.0.1:8990
info:
  contact:
    email: 1213604254@qq.com
    name: Aden
    url: https://adenzrx.xyz
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://adenzrx.xyz
  title: Swagger Example API
  version: "1.0"
paths:
  /login:
    get:
      consumes:
      - application/json
      description: 登录接口
      parameters:
      - description: 人名
        in: query
        name: who
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"response": "hello Razeen"}'
          schema:
            type: string
        "400":
          description: '{"response": "who are you"}'
          schema:
            type: string
      summary: Login
      tags:
      - 基础接口
swagger: "2.0"
