name: Melancholy

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  # job id
  build_image:
    name: BuildJob
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

#      - name: Build
#        run: go build -v ./...

  # job id
  test_all:
    name: TestJob
    runs-on: ubuntu-latest
    # build job before test job
    needs:
      - build
